#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     conveyor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     armConveyor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     shooter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     LEDS,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    rightArm,             tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    leftArm,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void drive() //logarithmic tank drive
{
  float y1Temp, x2Temp;
  short joyX = joystick.joy1_y1;
  short joyY = joystick.joy1_x2;


  if (joyY >= 0)
  {
  	y1Temp = ((joyY * joyY) / (128.0 * 128.0));
  }
  else
  {
  	y1Temp = ((joyY * joyY) / (128.0 * -128.0));
  }

  if (joyX >= 0)
  {
  	x2Temp = ((joyX * joyX) / (128.0 * -128.0));
  }
  else
  {
  	x2Temp = ((joyX * joyX) / (128.0 * 128.0));
  }

  int y1 = y1Temp * 100;
  int x2 = x2Temp * 100;

  if (abs (y1) < 10)
  {
  	y1 = 0;
  }

  if (abs (x2) < 10)
  {
    x2 = 0;
  }

  int rightSpeed = y1 + x2 * 2;
  int leftSpeed = y1 - x2 * 2;

  motor[rightDrive] = rightSpeed;
  motor[leftDrive] = leftSpeed;
}


/*bool toggleLoader(bool curVal) {
	if (joy1Btn(4)) {
		curVal = !curVal;
  }
  if (curVal) {
    motor[loader] = 100;
  } else {
  	motor[loader] = 0;
  }
  wait10Msec(10);
  return curVal;
}*/

/*bool toggleCollector(bool curVal) {
	if (joy1Btn(3)) {
		curVal = !curVal;
  }
  if (curVal) {
    motor[collector] = 100;
  } else {
  	motor[collector] = 0;
  }
  wait10Msec(10);
  return curVal;
}*/


//rtrig = turn in servo both
//rbump = turn conveyor in
//lbump = turn conveyor out
//ltrig = shoot in bsket


void checkButtons()
{
	if(joy1Btn(1)) //lift
	{
		motor[lift1] = 100;
		motor[lift2] = 100;
	}
	else if(joy1Btn(3)) //lower
	{
		motor[lift1] = -100;
		motor[lift2] = -100;
	}
	else
	{
		motor[lift1] = 0;
		motor[lift2] = 0;
	}

	if(joy1Btn(2)) //turn conveyor on arms
	{
		motor[armConveyor] = 100;
	}
	else
	{
		motor[armConveyor] = 0;
	}

	if (joy1Btn(7)) //shooter
	{
		motor[shooter] = 100;
  }
  else
  {
    motor[shooter] = 0;
  }

  if (joy1Btn(6)) //conveyor for loader
  {
		motor[conveyor] = 100;
  }
  else if (joy1Btn(5)) //reverse conveyor for loader
  {
		motor[conveyor] = -100;
  }
  else
  {
    motor[conveyor] = 0;
  }

  if(joy1Btn(8)) //bring arms together
  {
  	servo[rightArm] = 20;
  	servo[leftArm] = 20;
  }
  else //separate arms when button not pressed
  {
  	servo[rightArm] = 0;
  	servo[leftArm] = 0;
  }
}

void ledControl(short button, int value, int cnt)
{
	if(button == 0)
	{
		motor[LEDs] = 100;
	}
	else if(button == 2)
	{
		motor[LEDs] = value;
	}
	else if(button == 4)
	{
		motor[LEDs] = 0;
	}
	else if(button == 6)
	{
		if ((cnt > 45) || ((cnt > 20) && (cnt < 25)))
		{
			motor[LEDs] = 100;
	  }
	  else if (cnt == 0)
	  {
		  motor[LEDs] = 0;
	  }
	}
}

short checkDPad(short button)
{
	if(joystick.joy1_TopHat == 0)
	{
		return 0;
	}
	else if(joystick.joy1_TopHat == 2)
	{
		return 2;
	}
	else if(joystick.joy1_TopHat == 4)
	{
		return 4;
	}
	else if(joystick.joy1_TopHat == 6)
	{
		return 6;
	}
	else
	{
		return button;
	}
}

task main()
{
  waitForStart();   // wait for start of tele-op phase
  ClearTimer(T1);
	short button = -1;
	int value = 0;
	bool inc = true;
	int counter = 0;
	motor[LEDs] = 0;

  while (true)
  {
	  drive();
	  checkButtons();
	  button = checkDPad(button);
		ledControl(button, value, counter);

		// LED Pulse
		if(inc)
		{
		  value++;
		  if (value == 100)
		  {
		     inc = false;
		  }
	  }
	  else
	  {
	    value--;
		  if (value == 0)
		  {
		     inc = true;
			}
	  }

	  // LED Flash
	  counter++;
	  if (counter == 51)
	  {
	  	counter = 0;
	  }

		wait1Msec(5);


  }
}
